### ISSUE TITLE
closes immediately

### ISSUE THREAD

**Issue by Retardcode** [secanon0/HPomb#11]
I'm sorry if this is dumb, I don't do anything on python, i just wanted to prank my friend. however, whenever I open it, it immediately closes. Thanks. (OS used is Windows 10)

**Comment by secanon0** [comment]
Please check your python version 
It's required 3.x

> Python -v

And check pybase64 & openapi-codec module Install 

> pip3 install openapi-codec

> pip3 install pybase64

And use cmd to run this program
